# Generated by Django 5.2.4 on 2025-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_app", "0002_remove_customuser_car_model_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("term", models.CharField(max_length=120)),
                ("short_def", models.CharField(max_length=300)),
                ("long_def", models.TextField(blank=True)),
                ("category", models.CharField(db_index=True, max_length=60)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("related", models.JSONField(blank=True, default=list)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["term"],
                "indexes": [
                    models.Index(fields=["term"], name="insurance_a_term_dd55cd_idx"),
                    models.Index(
                        fields=["category"], name="insurance_a_categor_b1dded_idx"
                    ),
                ],
            },
        ),
    ]
