# Generated by Django 5.2.4 on 2025-08-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_app", "0003_glossaryterm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insurancequote",
            options={"ordering": ["-created_at"]},
        ),
    ]
